GearRemove = (vehicle player);
removeAllWeapons GearRemove;
removeAllItems GearRemove;
removebackpack GearRemove;

GearAdd = (vehicle player);
GearAdd addWeapon 'SCAR_H_LNG_Sniper_SD';
GearAdd addMagazine '20Rnd_762x51_SB_SCAR';
GearAdd addMagazine '20Rnd_762x51_SB_SCAR';
GearAdd addMagazine '20Rnd_762x51_SB_SCAR';
GearAdd addMagazine '20Rnd_762x51_SB_SCAR';
GearAdd addMagazine '20Rnd_762x51_SB_SCAR';
GearAdd addMagazine '20Rnd_762x51_SB_SCAR';
GearAdd addMagazine '20Rnd_762x51_SB_SCAR';
GearAdd addMagazine 'ItemBloodbag';
GearAdd addMagazine 'ItemPainkiller'; 
GearAdd addMagazine 'ItemEpinephrine';
GearAdd addMagazine 'ItemMorphine';
GearAdd addWeapon 'UZI_SD_EP1';
GearAdd addMagazine '30Rnd_9x19_UZI_SD';
GearAdd addMagazine '30Rnd_9x19_UZI_SD';
GearAdd addMagazine '30Rnd_9x19_UZI_SD';
GearAdd addMagazine '30Rnd_9x19_UZI_SD';
GearAdd addMagazine 'ItemBandage';
GearAdd addMagazine 'ItemBandage';
GearAdd addMagazine 'ItemBandage';
GearAdd addMagazine 'ItemBandage';
GearAdd addWeapon 'Binocular_Vector';
GearAdd addWeapon 'NVGoggles';
GearAdd addWeapon 'ItemHatchet';
GearAdd addWeapon 'ItemMatchbox';
GearAdd addWeapon 'ItemEtool';
GearAdd addWeapon 'ItemToolbox';
GearAdd addWeapon 'ItemCrowbar';
GearAdd addWeapon 'ItemGPS';
GearAdd addWeapon 'ItemKnife';
GearAdd addWeapon 'ItemRadio';
GearAdd addBackpack 'DZ_LargeGunBag_EP1';
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemBloodbag', 3];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemSodaPepsi', 5];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemBandage', 3];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['FoodSteakCooked', 5];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemMorphine', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemAntibiotic', 1];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemPainkiller', 1];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemEpinephrine', 1];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemGoldBar10oz', 8];
