GearRemove = (vehicle player);
removeAllWeapons GearRemove;
removeAllItems GearRemove;
removebackpack GearRemove;

GearAdd = (vehicle player);
GearAdd addWeapon 'm8_holo_sd';
GearAdd addMagazine '30Rnd_556x45_StanagSD';
GearAdd addMagazine '30Rnd_556x45_StanagSD';
GearAdd addMagazine '30Rnd_556x45_StanagSD';
GearAdd addMagazine '20Rnd_762x51_B_SCAR';
GearAdd addMagazine '20Rnd_762x51_B_SCAR';
GearAdd addMagazine '20Rnd_762x51_B_SCAR';
GearAdd addWeapon 'M9SD';
GearAdd addMagazine 'ItemBandage';
GearAdd addMagazine 'ItemBandage';
GearAdd addMagazine 'ItemBandage';
GearAdd addMagazine 'ItemBandage';
GearAdd addMagazine '15Rnd_9x19_M9SD';
GearAdd addMagazine '15Rnd_9x19_M9SD';
GearAdd addMagazine '15Rnd_9x19_M9SD';
GearAdd addWeapon 'Binocular_Vector';
GearAdd addWeapon 'NVGoggles';
GearAdd addWeapon 'ItemCompass';
GearAdd addWeapon 'ItemMap';
GearAdd addWeapon 'ItemWatch';
GearAdd addWeapon 'ItemHatchet';
GearAdd addWeapon 'ItemKnife';
GearAdd addWeapon 'Itemmatchbox';
GearAdd addWeapon 'Itemetool';
GearAdd addWeapon 'Itemtoolbox';
GearAdd addWeapon 'ItemCrowbar';
GearAdd addWeapon 'ItemGPS';
GearAdd addBackpack 'DZ_LargeGunBag_EP1';
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemBloodbag', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemWaterbottleBoiled', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['FoodSteakCooked', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemMorphine', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemGoldBar10oz', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['TrashTinCan', 1];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemAntibiotic', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemPainkiller', 2];
(Unitbackpack GearAdd) addWeaponCargoGlobal ['M110_NVG_EP1', 1];