GearAdd = (vehicle player);
GearAdd addMagazine 'ItemGoldBar10oz';
GearAdd addMagazine 'ItemGoldBar10oz';
GearAdd addMagazine 'ItemGoldBar10oz';
GearAdd addMagazine 'ItemGoldBar10oz';
GearAdd addMagazine 'ItemGoldBar10oz';
GearAdd addMagazine 'ItemGoldBar10oz';
GearAdd addMagazine 'ItemGoldBar10oz';
GearAdd addMagazine 'ItemGoldBar10oz';
GearAdd addMagazine 'ItemGoldBar10oz';
GearAdd addMagazine 'ItemGoldBar10oz';
GearAdd addMagazine 'ItemGoldBar10oz';
GearAdd addMagazine 'ItemGoldBar10oz';