GearRemove = (vehicle player);
removeAllWeapons GearRemove;
removeAllItems GearRemove;
removebackpack GearRemove;

GearAdd = (vehicle player);
GearAdd addWeapon 'M4A1_HWS_GL_SD_Camo';
GearAdd addMagazine '30Rnd_556x45_StanagSD';
GearAdd addMagazine '30Rnd_556x45_StanagSD';
GearAdd addMagazine '30Rnd_556x45_StanagSD';
GearAdd addMagazine 'ItemBloodbag';
GearAdd addMagazine 'ItemMorphine';
GearAdd addMagazine 'ItemPainkiller'; 
GearAdd addMagazine 'ItemEpinephrine';
GearAdd addMagazine 'ItemWaterbottleBoiled';
GearAdd addMagazine 'FoodSteakCooked';
GearAdd addWeapon 'glock17_EP1';
GearAdd addMagazine 'ItemBandage';
GearAdd addMagazine 'ItemBandage';
GearAdd addMagazine 'ItemBandage';
GearAdd addMagazine 'ItemBandage';
GearAdd addMagazine '17Rnd_9x19_glock17';
GearAdd addMagazine '17Rnd_9x19_glock17';
GearAdd addMagazine 'FlareWhite_M203';
GearAdd addMagazine '1Rnd_HE_M203';
GearAdd addWeapon 'Binocular_Vector';
GearAdd addWeapon 'NVGoggles';
GearAdd addWeapon 'ItemCompass';
GearAdd addWeapon 'ItemMap';
GearAdd addWeapon 'ItemWatch';
GearAdd addWeapon 'ItemHatchet';
GearAdd addWeapon 'ItemKnife';
GearAdd addWeapon 'Itemmatchbox';
GearAdd addWeapon 'Itemetool';
GearAdd addWeapon 'Itemtoolbox';
GearAdd addWeapon 'ItemCrowbar';
GearAdd addWeapon 'ItemGPS';
GearAdd addBackpack 'DZ_LargeGunBag_EP1';
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemBloodbag', 1];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemMorphine', 1];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemPainkiller', 1];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['30Rnd_556x45_StanagSD', 3];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemWaterbottleBoiled', 4];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemBandage', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['FoodSteakCooked', 4];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemGoldBar10oz', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['TrashTinCan', 1];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['FlareWhite_M203', 1];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['1Rnd_HE_M203', 1];
(Unitbackpack GearAdd) addWeaponCargoGlobal ['SCAR_H_CQC_CCO', 1];
(Unitbackpack GearAdd) addWeaponCargoGlobal ['SCAR_H_STD_EGLM_Spect', 1];
(Unitbackpack GearAdd) addWeaponCargoGlobal ['SCAR_H_CQC_CCO_SD', 1];
(Unitbackpack GearAdd) addWeaponCargoGlobal ['SCAR_H_LNG_Sniper', 1];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['20Rnd_762x51_DMR', 6];